import fs from 'node:fs';
import PDFDocument from 'pdfkit';
import { LEVEL_LABELS, METRICS, formatScore } from './metrics.js';

export const PDF_MIME = 'application/pdf';

// DejaVu ships with the base OS and covers the full Unicode range, so article titles and
// discussion bodies cannot come out as mojibake. pdfkit's built-in Helvetica is WinAnsi
// only, so it is kept strictly as a fallback.
const FONT_REGULAR = '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf';
const FONT_BOLD = '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf';

const MARGIN = 40;
const INK = '#111111';
const MUTED = '#4a4a4a';
const RULE = '#c9c9c4';
const ACCENT = '#ffeb3b';
const PANEL = '#f7f7f1';

const LEVEL_FILL = {
  high: '#d9f2e1',
  medium: '#ececec',
  low: '#fdeccd',
  idle: '#fdeccd',
  never: '#fadcdc',
};

function registerFonts(doc) {
  if (fs.existsSync(FONT_REGULAR) && fs.existsSync(FONT_BOLD)) {
    doc.registerFont('body', FONT_REGULAR);
    doc.registerFont('bold', FONT_BOLD);
    return { body: 'body', bold: 'bold' };
  }
  return { body: 'Helvetica', bold: 'Helvetica-Bold' };
}

// The team works in WIB and the db pool is pinned to +07:00, so a report generated at 01:00
// must not be stamped with the previous day just because the server clock is UTC.
const WIB_OFFSET_MS = 7 * 60 * 60 * 1000;

function wibParts(date) {
  return new Date(date.getTime() + WIB_OFFSET_MS).toISOString();
}

// Down to the minute, because the file name is what tells two downloads apart on disk: the
// day alone means every download in one day lands on the same name.
export function reportFileStamp(date) {
  return wibParts(date).slice(0, 16).replace('T', '-').replace(':', '');
}

function wibDateTime(date) {
  return wibParts(date).replace('T', ' ').slice(0, 16);
}

// pdfkit never clips or ellipsizes on its own, so anything going into a fixed-width cell
// has to be measured and shortened by hand.
function fit(doc, text, font, size, maxWidth) {
  doc.font(font).fontSize(size);
  const value = String(text ?? '');
  if (doc.widthOfString(value) <= maxWidth) return value;

  let cut = value;
  while (cut.length > 1 && doc.widthOfString(`${cut}…`) > maxWidth) {
    cut = cut.slice(0, -1);
  }
  return `${cut}…`;
}

// Resolves with the finished PDF as a Buffer instead of piping to the response, so the route
// can send a Content-Length and so a failure halfway through drawing produces a clean error
// rather than a truncated file the client has already been told is a 200.
export async function buildStaffReportPdf(options) {
  const doc = new PDFDocument({
    size: 'A4',
    margin: MARGIN,
    bufferPages: true,
    info: { Title: 'E-Journey — Staff Activity Report', Author: options.generatedBy },
  });

  const chunks = [];
  const finished = new Promise((resolve, reject) => {
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  drawReport(doc, options);
  doc.end();

  return finished;
}

function drawReport(doc, { report, details, days, generatedBy, generatedAt, detailLimit }) {
  const fonts = registerFonts(doc);
  const pageW = doc.page.width;
  const pageH = doc.page.height;
  const contentW = pageW - MARGIN * 2;
  const bottom = pageH - MARGIN;

  let y = MARGIN;

  function rule(width = contentW, x = MARGIN, color = RULE, thickness = 1) {
    doc.moveTo(x, y).lineTo(x + width, y).lineWidth(thickness).stroke(color);
  }

  function ensure(needed) {
    if (y + needed <= bottom) return;
    doc.addPage();
    y = MARGIN;
    drawRunningHead();
  }

  function drawRunningHead() {
    doc.font(fonts.bold).fontSize(8).fillColor(MUTED);
    doc.text('E-Journey — Staff Activity Report', MARGIN, y, { lineBreak: false });
    doc.font(fonts.body).fontSize(8);
    doc.text(`last ${days} days`, MARGIN, y, { width: contentW, align: 'right', lineBreak: false });
    y += 12;
    rule();
    y += 10;
  }

  // ---------- masthead ----------

  const bandH = 84;
  doc.rect(0, 0, pageW, bandH).fill(ACCENT);
  doc.moveTo(0, bandH).lineTo(pageW, bandH).lineWidth(3).stroke(INK);

  doc.font(fonts.body).fontSize(8).fillColor(INK);
  doc.text('E-JOURNEY  ·  ADMIN REPORT', MARGIN, 22, { lineBreak: false });
  doc.font(fonts.bold).fontSize(21);
  doc.text('Staff Activity Report', MARGIN, 36, { lineBreak: false });

  y = bandH + 26;

  // Meta line, three columns.
  const metaCols = [
    { label: 'Generated', value: wibDateTime(generatedAt) },
    { label: 'Window', value: `Last ${days} days` },
    { label: 'Generated by', value: generatedBy },
  ];
  const metaColW = contentW / metaCols.length;
  metaCols.forEach((col, index) => {
    const x = MARGIN + index * metaColW;
    doc.font(fonts.body).fontSize(7).fillColor(MUTED);
    doc.text(col.label.toUpperCase(), x, y, { lineBreak: false });
    doc.font(fonts.bold).fontSize(10).fillColor(INK);
    doc.text(fit(doc, col.value, fonts.bold, 10, metaColW - 12), x, y + 10, { lineBreak: false });
  });
  y += 34;

  // ---------- headline numbers ----------

  const cards = [
    { label: 'STAFF', value: report.team.staffCount },
    { label: 'CONTRIBUTING', value: report.team.reportingCount },
    { label: 'GONE QUIET', value: report.team.idleCount },
    { label: 'TOTAL SCORE', value: formatScore(report.team.totalScore) },
  ];
  const cardGap = 10;
  const cardW = (contentW - cardGap * (cards.length - 1)) / cards.length;
  const cardH = 52;

  cards.forEach((card, index) => {
    const x = MARGIN + index * (cardW + cardGap);
    doc.roundedRect(x, y, cardW, cardH, 6).fillAndStroke(PANEL, INK);
    doc.font(fonts.bold).fontSize(17).fillColor(INK);
    doc.text(String(card.value), x + 12, y + 12, { lineBreak: false });
    doc.font(fonts.body).fontSize(7).fillColor(MUTED);
    doc.text(card.label, x + 12, y + 34, { lineBreak: false });
  });
  y += cardH + 26;

  // ---------- summary table ----------

  doc.font(fonts.bold).fontSize(12).fillColor(INK);
  doc.text('Summary', MARGIN, y, { lineBreak: false });
  y += 18;

  // The weight rides along under each metric header; without it the row looks like a broken
  // sum, because the four count columns deliberately do not add up to the score. The widths
  // are what is left after the four fixed columns, so the header label has to stay short —
  // "REPLIES ×1" on one line does not fit. State holds the longest level label ("Never
  // contributed"), Staff the widest "name (@handle)" pair.
  const fixedWidths = [22, 134, 44, 104];
  const metricW = (contentW - fixedWidths.reduce((a, b) => a + b, 0)) / METRICS.length;
  const columns = [
    { label: '#', width: fixedWidths[0], align: 'left' },
    { label: 'Staff', width: fixedWidths[1], align: 'left' },
    { label: 'Score', width: fixedWidths[2], align: 'right' },
    { label: 'State', width: fixedWidths[3], align: 'left' },
    ...METRICS.map((metric) => ({
      label: metric.short,
      sub: `×${formatScore(metric.weight)}`,
      width: metricW,
      align: 'right',
    })),
  ];

  function cellX(index) {
    let x = MARGIN;
    for (let i = 0; i < index; i += 1) x += columns[i].width;
    return x;
  }

  function tableHead() {
    const headH = 28;
    ensure(headH + 34);

    doc.rect(MARGIN, y, contentW, headH).fill(PANEL);
    doc.moveTo(MARGIN, y).lineTo(MARGIN + contentW, y).lineWidth(2).stroke(INK);
    doc.moveTo(MARGIN, y + headH).lineTo(MARGIN + contentW, y + headH).lineWidth(1).stroke(INK);
    columns.forEach((col, index) => {
      const x = cellX(index) + 6;
      const width = col.width - 12;

      doc.font(fonts.bold).fontSize(7).fillColor(INK);
      doc.text(fit(doc, col.label.toUpperCase(), fonts.bold, 7, width), x, y + 6, {
        width,
        align: col.align,
        lineBreak: false,
      });

      if (!col.sub) return;
      doc.font(fonts.body).fontSize(6.5).fillColor(MUTED);
      doc.text(fit(doc, col.sub, fonts.body, 6.5, width), x, y + 16, {
        width,
        align: col.align,
        lineBreak: false,
      });
    });
    y += headH;
  }

  tableHead();

  report.staff.forEach((person) => {
    ensure(26);
    const rowH = 24;

    doc.rect(MARGIN, y, contentW, rowH).fill(LEVEL_FILL[person.level] ?? PANEL);

    const cells = [
      String(person.rank),
      `${person.user.fullName}  (@${person.user.username})`,
      formatScore(person.score),
      LEVEL_LABELS[person.level] ?? person.level,
      ...METRICS.map((metric) => String(person.counts[metric.key])),
    ];

    cells.forEach((value, index) => {
      const col = columns[index];
      const x = cellX(index) + 6;
      const width = col.width - 12;
      // The name column and the total are the two things the eye lands on.
      const emphasis = index === 1 || index === 2;
      const font = emphasis ? fonts.bold : fonts.body;
      const size = index === 1 ? 9 : 8.5;

      doc.font(font).fontSize(size).fillColor(INK);
      doc.text(fit(doc, value, font, size, width), x, y + 8, {
        width,
        align: col.align,
        lineBreak: false,
      });
    });

    y += rowH;
    doc.moveTo(MARGIN, y).lineTo(MARGIN + contentW, y).lineWidth(0.5).stroke(RULE);
  });

  y += 8;
  const note =
    'Each contribution is multiplied by its weight before it is added up — ' +
    METRICS.map((metric) => `${metric.label} ×${formatScore(metric.weight)}`).join(', ') +
    '. Sign-ins, schedule entries and appearance changes are recorded by the app but not scored.';
  doc.font(fonts.body).fontSize(8).fillColor(MUTED);
  // Measured rather than assumed: the weights make this line long enough to wrap.
  const noteH = doc.heightOfString(note, { width: contentW });
  ensure(noteH + 14);
  doc.text(note, MARGIN, y, { width: contentW });
  y += noteH + 14;

  // ---------- per-member detail ----------

  report.staff.forEach((person) => {
    const detail = details.get(person.user.id) ?? { entries: [], truncated: false };

    ensure(64);
    y += 10;

    doc.rect(MARGIN, y, 6, 22).fill(ACCENT);
    doc.font(fonts.bold).fontSize(12).fillColor(INK);
    doc.text(
      `${person.rank}.  ${person.user.fullName}`,
      MARGIN + 14,
      y + 4,
      { lineBreak: false }
    );
    doc.font(fonts.body).fontSize(8).fillColor(MUTED);
    doc.text(
      `Score ${formatScore(person.score)}  ·  ${LEVEL_LABELS[person.level] ?? person.level}`,
      MARGIN,
      y + 4,
      { width: contentW, align: 'right', lineBreak: false }
    );
    y += 30;

    // Column layout for the detail lines: date, kind, what it was.
    const dateW = 88;
    const kindW = 76;
    const titleW = contentW - dateW - kindW - 16;

    if (!detail.entries.length) {
      doc.font(fonts.body).fontSize(9).fillColor(MUTED);
      doc.text('No contributions in this window.', MARGIN, y, { lineBreak: false });
      y += 16;
      return;
    }

    detail.entries.forEach((entry) => {
      const kind = METRICS.find((metric) => metric.key === entry.type);
      const date = String(entry.createdAt).slice(0, 16);
      // Reserve the whole entry up front — otherwise a page break can land between the
      // heading line and its excerpt.
      ensure(entry.detail ? 31 : 18);

      doc.font(fonts.body).fontSize(8).fillColor(MUTED);
      doc.text(date, MARGIN, y, { width: dateW, lineBreak: false });

      doc.font(fonts.body).fontSize(8).fillColor(INK);
      doc.text(fit(doc, kind?.label ?? entry.type, fonts.body, 8, kindW - 8), MARGIN + dateW, y, {
        width: kindW - 8,
        lineBreak: false,
      });

      doc.font(fonts.bold).fontSize(8.5).fillColor(INK);
      doc.text(fit(doc, entry.title, fonts.bold, 8.5, titleW), MARGIN + dateW + kindW, y, {
        width: titleW,
        lineBreak: false,
      });
      y += 12;

      // The excerpt / URL is what makes the line useful, but it must not push the row
      // rhythm around, so it gets a single clipped line of its own.
      if (entry.detail) {
        doc.font(fonts.body).fontSize(7.5).fillColor(MUTED);
        doc.text(
          fit(doc, entry.detail, fonts.body, 7.5, titleW + kindW - 8),
          MARGIN + dateW,
          y,
          { width: titleW + kindW - 8, lineBreak: false }
        );
        y += 12;
      }

      doc.moveTo(MARGIN + dateW, y + 1).lineTo(MARGIN + contentW, y + 1).lineWidth(0.4).stroke(RULE);
      y += 5;
    });

    if (detail.truncated) {
      ensure(16);
      doc.font(fonts.body).fontSize(7.5).fillColor(MUTED);
      doc.text(
        `Only the ${detailLimit} most recent contributions are listed.`,
        MARGIN,
        y,
        { lineBreak: false }
      );
      y += 14;
    }
  });

  // ---------- footers ----------

  const range = doc.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    // Zeroing the bottom margin keeps these absolute writes from triggering a page break.
    doc.page.margins.bottom = 0;
    const footerY = pageH - MARGIN + 12;
    doc.moveTo(MARGIN, footerY - 8).lineTo(MARGIN + contentW, footerY - 8).lineWidth(0.5).stroke(RULE);
    doc.font(fonts.body).fontSize(7.5).fillColor(MUTED);
    doc.text('E-Journey — internal report', MARGIN, footerY, { lineBreak: false });
    doc.text(
      `Page ${index - range.start + 1} of ${range.count}`,
      MARGIN,
      footerY,
      { width: contentW, align: 'right', lineBreak: false }
    );
  }
}
